#콜론뒤 띄어쓰기 항상!

#server.port=8080
server: 
  port: 8080

#spring.datasource.driver-class-name
spring: 
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@14.36.141.71:10052:xe
#    username: rocket_test2
#    password: rocket_test2
    username: rocket_erp
    password: rocket_erp
    hikari:
      maximum-pool-size: 3
      minimum-idle: 19
      idle-timeout: 50
#spring.mvc.view.prfix/suffix
  mvc: 
    view: 
      suffix: .jsp
      prefix: /WEB-INF/views/
#sping email 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimsj9693@gmail.com
    password: jxodcepymhzmthil
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          
#mybatis 설정
mybatis: 
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:config/mybatis-config.xml

#log 설정
logging: 
  level: 
    '[com.bs.rocket]': debug