#콜론뒤 띄어쓰기 항상!

#server.port=8080
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    max-http-header-size: 819200

    #    spring.datasource.driver-class-name
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@14.36.141.71:10052:xe
    username: rocket_erp
    password: rocket_erp
    #                username: rocket_erp
    #                password: rocket_erp
    #spring:
    #  datasource:
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    #    username: erptest02
    #    password: erptest02
    #        username: rocket_erp
    #        password: rocket_erp
    hikari:
      maximum-pool-size: 24
      minimum-idle: 19
      idle-timeout: 50
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #spring.mvc.view.prfix/suffix
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  #sping email 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimsj9693@gmail.com
    password: jxodcepymhzmthil
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  aop:
    auto: true
  #  web:
  #    resources:
  #      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
  devtools:
    #    restart:
    #      enabled: false
    livereload:
      enabled: true

#mybatis 설정
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:config/mybatis-config.xml
#log 설정
logging:
  level:
    '[com.rocket]': debug
    '[jdbc.sqlonly]': off
    '[jdbc.resultsettable]': debug
    '[jdbc.audit]': off
    '[jdbc.resultset]': off
    '[jdbc.connection]': error
    '[jdbc.sqltiming]': debug
    '[org.springframework.web]': info

pattern:
  console: "%d{yyyy/MM/dd HH:mm:ss.SSS} %-5level --- [%thread] %logger[%method:%line] - %msg  - ResultSet: %msg %rowCount row(s)%n"